Add Control Module new game endpoint - Fixes #24
AxelCB/DSA-AdminDesafios pull request #39
Opened 2017-05-12 06:21 UTC by mokocchi

Reset users and teams and connect to user admin for new ones.

The user import [json ](https://gist.github.com/mokocchi/f1a619eb7724439c57d0e71517130e40#file-equipos-json) (copied from the specification) specifies ids which are used later to make requests, but hibernate ignores them and uses the insert number (sequence). So I created extra variables to store the original id (teamId and playerId) and use those instead.

I also made a little mock for the userAdmin module in python [here](https://gist.github.com/mokocchi/f1a619eb7724439c57d0e71517130e40#file-server-py). It waits for a request in port 2222 and sends a http response with the json in equipos.json (which must be in the same folder). I can add token support to the mock later when that branch gets merged. Also you can try one of: changing the port in Application.java / changing the apache port / connecting via netcat.

2017-05-13 22:52 UTC, AxelCB requested changes
I think it would be necessary to make the user admin URL configurable somewhere, though if you want to, we can create another issue with that

2017-05-13 22:52 UTC, AxelCB commented on Backend/src/main/java/ar/edu/unlp/dsa/controller/ConfigurationRestController.java
> +		String teamsImportUrl = "http://localhost:"+Application.USER_ADMIN_PORT+"/listado_de_equipos_y_usuarios";
I think this URL should be parameterized somewhere, as in a config file or something. The real/production version could be somewhere else (like in another host).

2017-05-13 22:52 UTC, AxelCB commented on Backend/src/main/java/ar/edu/unlp/dsa/controller/ConfigurationRestController.java
> +			Team team = this.getMapper().map(equipo, Team.class);
I think this could be solved using nested mappings from dozer, but I don't really care if it's like this if we can give in the first version

2017-05-15 03:24 UTC, mokocchi commented on Backend/src/main/java/ar/edu/unlp/dsa/controller/ConfigurationRestController.java
> +		String teamsImportUrl = "http://localhost:"+Application.USER_ADMIN_PORT+"/listado_de_equipos_y_usuarios";
done

2017-05-15 03:30 UTC, mokocchi commented on Backend/src/main/java/ar/edu/unlp/dsa/controller/ConfigurationRestController.java
> +			Team team = this.getMapper().map(equipo, Team.class);
You're right. Add this as enhancement issue to refactor it after the first version.

2017-05-15 11:36 UTC, AxelCB approved these changes

2017-05-15 11:39 UTC, merged

2017-05-15 11:40 UTC, AxelCB commented
Just realized about issue #32